# A descriptive name for your workflow
name: Build and Push Geyser Image

# This workflow runs on any push to the 'main' branch
on:
  push:
    branches: [ "main" ]

# ADDED: Define variables here for easy updates in the future
env:
  DOCKERHUB_REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}/geyser
  CONTAINER_NAME: geyser

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        # This combines QEMU and Buildx setup into one step
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        # UPDATED: Using latest version of the action
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ADDED: This step creates smart tags like :latest, :v1.2.3, etc. automatically
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_REGISTRY }}

      - name: Build and push image
        # UPDATED: Using latest version and adding caching
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # ADDED: Caching from the registry to speed up future builds significantly
          #cache-from: type=registry,ref=${{ env.DOCKERHUB_REGISTRY }}:buildcache
          #cache-to: type=registry,ref=${{ env.DOCKERHUB_REGISTRY }}:buildcache,mode=max
          no-cache: true

  # REMOVED: The entire 'deploy-to-droplet' job is gone.
  # Watchtower now handles this part automatically on the server.
